/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GetstartedRouteImport } from './routes/getstarted'
import { Route as IndexRouteImport } from './routes/index'
import { Route as dashboardWalletIndexRouteImport } from './routes/(dashboard)/wallet/index'
import { Route as dashboardUsersIndexRouteImport } from './routes/(dashboard)/users/index'
import { Route as dashboardSummaryIndexRouteImport } from './routes/(dashboard)/summary/index'
import { Route as dashboardSkillsIndexRouteImport } from './routes/(dashboard)/skills/index'
import { Route as dashboardSettingsIndexRouteImport } from './routes/(dashboard)/settings/index'
import { Route as dashboardResolutionIndexRouteImport } from './routes/(dashboard)/resolution/index'
import { Route as dashboardMarketPlaceIndexRouteImport } from './routes/(dashboard)/marketPlace/index'
import { Route as dashboardCategoryRequestIndexRouteImport } from './routes/(dashboard)/categoryRequest/index'
import { Route as dashboardAccountIndexRouteImport } from './routes/(dashboard)/account/index'
import { Route as dashboardUsersUserIdRouteImport } from './routes/(dashboard)/users/$userId'
import { Route as dashboardSkillsCategoryIdIndexRouteImport } from './routes/(dashboard)/skills/$categoryId/index'
import { Route as dashboardMarketPlaceMarketPlaceIdIndexRouteImport } from './routes/(dashboard)/marketPlace/$marketPlaceId/index'
import { Route as dashboardSkillsCategoryIdSubCategoryIdRouteImport } from './routes/(dashboard)/skills/$categoryId/$subCategoryId'
import { Route as dashboardMarketPlaceMarketPlaceIdChatRouteImport } from './routes/(dashboard)/marketPlace/$marketPlaceId/chat'
import { Route as dashboardMarketPlaceMarketPlaceIdMarketPlaceIdRouteImport } from './routes/(dashboard)/marketPlace/$marketPlaceId/$marketPlaceId'

const GetstartedRoute = GetstartedRouteImport.update({
  id: '/getstarted',
  path: '/getstarted',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardWalletIndexRoute = dashboardWalletIndexRouteImport.update({
  id: '/(dashboard)/wallet/',
  path: '/wallet/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardUsersIndexRoute = dashboardUsersIndexRouteImport.update({
  id: '/(dashboard)/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardSummaryIndexRoute = dashboardSummaryIndexRouteImport.update({
  id: '/(dashboard)/summary/',
  path: '/summary/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardSkillsIndexRoute = dashboardSkillsIndexRouteImport.update({
  id: '/(dashboard)/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardSettingsIndexRoute = dashboardSettingsIndexRouteImport.update({
  id: '/(dashboard)/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardResolutionIndexRoute =
  dashboardResolutionIndexRouteImport.update({
    id: '/(dashboard)/resolution/',
    path: '/resolution/',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardMarketPlaceIndexRoute =
  dashboardMarketPlaceIndexRouteImport.update({
    id: '/(dashboard)/marketPlace/',
    path: '/marketPlace/',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardCategoryRequestIndexRoute =
  dashboardCategoryRequestIndexRouteImport.update({
    id: '/(dashboard)/categoryRequest/',
    path: '/categoryRequest/',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardAccountIndexRoute = dashboardAccountIndexRouteImport.update({
  id: '/(dashboard)/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardUsersUserIdRoute = dashboardUsersUserIdRouteImport.update({
  id: '/(dashboard)/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardSkillsCategoryIdIndexRoute =
  dashboardSkillsCategoryIdIndexRouteImport.update({
    id: '/(dashboard)/skills/$categoryId/',
    path: '/skills/$categoryId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardMarketPlaceMarketPlaceIdIndexRoute =
  dashboardMarketPlaceMarketPlaceIdIndexRouteImport.update({
    id: '/(dashboard)/marketPlace/$marketPlaceId/',
    path: '/marketPlace/$marketPlaceId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardSkillsCategoryIdSubCategoryIdRoute =
  dashboardSkillsCategoryIdSubCategoryIdRouteImport.update({
    id: '/(dashboard)/skills/$categoryId/$subCategoryId',
    path: '/skills/$categoryId/$subCategoryId',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardMarketPlaceMarketPlaceIdChatRoute =
  dashboardMarketPlaceMarketPlaceIdChatRouteImport.update({
    id: '/(dashboard)/marketPlace/$marketPlaceId/chat',
    path: '/marketPlace/$marketPlaceId/chat',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardMarketPlaceMarketPlaceIdMarketPlaceIdRoute =
  dashboardMarketPlaceMarketPlaceIdMarketPlaceIdRouteImport.update({
    id: '/(dashboard)/marketPlace/$marketPlaceId/$marketPlaceId',
    path: '/marketPlace/$marketPlaceId/$marketPlaceId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/getstarted': typeof GetstartedRoute
  '/users/$userId': typeof dashboardUsersUserIdRoute
  '/account': typeof dashboardAccountIndexRoute
  '/categoryRequest': typeof dashboardCategoryRequestIndexRoute
  '/marketPlace': typeof dashboardMarketPlaceIndexRoute
  '/resolution': typeof dashboardResolutionIndexRoute
  '/settings': typeof dashboardSettingsIndexRoute
  '/skills': typeof dashboardSkillsIndexRoute
  '/summary': typeof dashboardSummaryIndexRoute
  '/users': typeof dashboardUsersIndexRoute
  '/wallet': typeof dashboardWalletIndexRoute
  '/marketPlace/$marketPlaceId/$marketPlaceId': typeof dashboardMarketPlaceMarketPlaceIdMarketPlaceIdRoute
  '/marketPlace/$marketPlaceId/chat': typeof dashboardMarketPlaceMarketPlaceIdChatRoute
  '/skills/$categoryId/$subCategoryId': typeof dashboardSkillsCategoryIdSubCategoryIdRoute
  '/marketPlace/$marketPlaceId': typeof dashboardMarketPlaceMarketPlaceIdIndexRoute
  '/skills/$categoryId': typeof dashboardSkillsCategoryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/getstarted': typeof GetstartedRoute
  '/users/$userId': typeof dashboardUsersUserIdRoute
  '/account': typeof dashboardAccountIndexRoute
  '/categoryRequest': typeof dashboardCategoryRequestIndexRoute
  '/marketPlace': typeof dashboardMarketPlaceIndexRoute
  '/resolution': typeof dashboardResolutionIndexRoute
  '/settings': typeof dashboardSettingsIndexRoute
  '/skills': typeof dashboardSkillsIndexRoute
  '/summary': typeof dashboardSummaryIndexRoute
  '/users': typeof dashboardUsersIndexRoute
  '/wallet': typeof dashboardWalletIndexRoute
  '/marketPlace/$marketPlaceId/$marketPlaceId': typeof dashboardMarketPlaceMarketPlaceIdMarketPlaceIdRoute
  '/marketPlace/$marketPlaceId/chat': typeof dashboardMarketPlaceMarketPlaceIdChatRoute
  '/skills/$categoryId/$subCategoryId': typeof dashboardSkillsCategoryIdSubCategoryIdRoute
  '/marketPlace/$marketPlaceId': typeof dashboardMarketPlaceMarketPlaceIdIndexRoute
  '/skills/$categoryId': typeof dashboardSkillsCategoryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/getstarted': typeof GetstartedRoute
  '/(dashboard)/users/$userId': typeof dashboardUsersUserIdRoute
  '/(dashboard)/account/': typeof dashboardAccountIndexRoute
  '/(dashboard)/categoryRequest/': typeof dashboardCategoryRequestIndexRoute
  '/(dashboard)/marketPlace/': typeof dashboardMarketPlaceIndexRoute
  '/(dashboard)/resolution/': typeof dashboardResolutionIndexRoute
  '/(dashboard)/settings/': typeof dashboardSettingsIndexRoute
  '/(dashboard)/skills/': typeof dashboardSkillsIndexRoute
  '/(dashboard)/summary/': typeof dashboardSummaryIndexRoute
  '/(dashboard)/users/': typeof dashboardUsersIndexRoute
  '/(dashboard)/wallet/': typeof dashboardWalletIndexRoute
  '/(dashboard)/marketPlace/$marketPlaceId/$marketPlaceId': typeof dashboardMarketPlaceMarketPlaceIdMarketPlaceIdRoute
  '/(dashboard)/marketPlace/$marketPlaceId/chat': typeof dashboardMarketPlaceMarketPlaceIdChatRoute
  '/(dashboard)/skills/$categoryId/$subCategoryId': typeof dashboardSkillsCategoryIdSubCategoryIdRoute
  '/(dashboard)/marketPlace/$marketPlaceId/': typeof dashboardMarketPlaceMarketPlaceIdIndexRoute
  '/(dashboard)/skills/$categoryId/': typeof dashboardSkillsCategoryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/getstarted'
    | '/users/$userId'
    | '/account'
    | '/categoryRequest'
    | '/marketPlace'
    | '/resolution'
    | '/settings'
    | '/skills'
    | '/summary'
    | '/users'
    | '/wallet'
    | '/marketPlace/$marketPlaceId/$marketPlaceId'
    | '/marketPlace/$marketPlaceId/chat'
    | '/skills/$categoryId/$subCategoryId'
    | '/marketPlace/$marketPlaceId'
    | '/skills/$categoryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/getstarted'
    | '/users/$userId'
    | '/account'
    | '/categoryRequest'
    | '/marketPlace'
    | '/resolution'
    | '/settings'
    | '/skills'
    | '/summary'
    | '/users'
    | '/wallet'
    | '/marketPlace/$marketPlaceId/$marketPlaceId'
    | '/marketPlace/$marketPlaceId/chat'
    | '/skills/$categoryId/$subCategoryId'
    | '/marketPlace/$marketPlaceId'
    | '/skills/$categoryId'
  id:
    | '__root__'
    | '/'
    | '/getstarted'
    | '/(dashboard)/users/$userId'
    | '/(dashboard)/account/'
    | '/(dashboard)/categoryRequest/'
    | '/(dashboard)/marketPlace/'
    | '/(dashboard)/resolution/'
    | '/(dashboard)/settings/'
    | '/(dashboard)/skills/'
    | '/(dashboard)/summary/'
    | '/(dashboard)/users/'
    | '/(dashboard)/wallet/'
    | '/(dashboard)/marketPlace/$marketPlaceId/$marketPlaceId'
    | '/(dashboard)/marketPlace/$marketPlaceId/chat'
    | '/(dashboard)/skills/$categoryId/$subCategoryId'
    | '/(dashboard)/marketPlace/$marketPlaceId/'
    | '/(dashboard)/skills/$categoryId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GetstartedRoute: typeof GetstartedRoute
  dashboardUsersUserIdRoute: typeof dashboardUsersUserIdRoute
  dashboardAccountIndexRoute: typeof dashboardAccountIndexRoute
  dashboardCategoryRequestIndexRoute: typeof dashboardCategoryRequestIndexRoute
  dashboardMarketPlaceIndexRoute: typeof dashboardMarketPlaceIndexRoute
  dashboardResolutionIndexRoute: typeof dashboardResolutionIndexRoute
  dashboardSettingsIndexRoute: typeof dashboardSettingsIndexRoute
  dashboardSkillsIndexRoute: typeof dashboardSkillsIndexRoute
  dashboardSummaryIndexRoute: typeof dashboardSummaryIndexRoute
  dashboardUsersIndexRoute: typeof dashboardUsersIndexRoute
  dashboardWalletIndexRoute: typeof dashboardWalletIndexRoute
  dashboardMarketPlaceMarketPlaceIdMarketPlaceIdRoute: typeof dashboardMarketPlaceMarketPlaceIdMarketPlaceIdRoute
  dashboardMarketPlaceMarketPlaceIdChatRoute: typeof dashboardMarketPlaceMarketPlaceIdChatRoute
  dashboardSkillsCategoryIdSubCategoryIdRoute: typeof dashboardSkillsCategoryIdSubCategoryIdRoute
  dashboardMarketPlaceMarketPlaceIdIndexRoute: typeof dashboardMarketPlaceMarketPlaceIdIndexRoute
  dashboardSkillsCategoryIdIndexRoute: typeof dashboardSkillsCategoryIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/getstarted': {
      id: '/getstarted'
      path: '/getstarted'
      fullPath: '/getstarted'
      preLoaderRoute: typeof GetstartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/wallet/': {
      id: '/(dashboard)/wallet/'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof dashboardWalletIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/users/': {
      id: '/(dashboard)/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof dashboardUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/summary/': {
      id: '/(dashboard)/summary/'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof dashboardSummaryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/skills/': {
      id: '/(dashboard)/skills/'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof dashboardSkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/settings/': {
      id: '/(dashboard)/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof dashboardSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/resolution/': {
      id: '/(dashboard)/resolution/'
      path: '/resolution'
      fullPath: '/resolution'
      preLoaderRoute: typeof dashboardResolutionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/marketPlace/': {
      id: '/(dashboard)/marketPlace/'
      path: '/marketPlace'
      fullPath: '/marketPlace'
      preLoaderRoute: typeof dashboardMarketPlaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/categoryRequest/': {
      id: '/(dashboard)/categoryRequest/'
      path: '/categoryRequest'
      fullPath: '/categoryRequest'
      preLoaderRoute: typeof dashboardCategoryRequestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/account/': {
      id: '/(dashboard)/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof dashboardAccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/users/$userId': {
      id: '/(dashboard)/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof dashboardUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/skills/$categoryId/': {
      id: '/(dashboard)/skills/$categoryId/'
      path: '/skills/$categoryId'
      fullPath: '/skills/$categoryId'
      preLoaderRoute: typeof dashboardSkillsCategoryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/marketPlace/$marketPlaceId/': {
      id: '/(dashboard)/marketPlace/$marketPlaceId/'
      path: '/marketPlace/$marketPlaceId'
      fullPath: '/marketPlace/$marketPlaceId'
      preLoaderRoute: typeof dashboardMarketPlaceMarketPlaceIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/skills/$categoryId/$subCategoryId': {
      id: '/(dashboard)/skills/$categoryId/$subCategoryId'
      path: '/skills/$categoryId/$subCategoryId'
      fullPath: '/skills/$categoryId/$subCategoryId'
      preLoaderRoute: typeof dashboardSkillsCategoryIdSubCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/marketPlace/$marketPlaceId/chat': {
      id: '/(dashboard)/marketPlace/$marketPlaceId/chat'
      path: '/marketPlace/$marketPlaceId/chat'
      fullPath: '/marketPlace/$marketPlaceId/chat'
      preLoaderRoute: typeof dashboardMarketPlaceMarketPlaceIdChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/marketPlace/$marketPlaceId/$marketPlaceId': {
      id: '/(dashboard)/marketPlace/$marketPlaceId/$marketPlaceId'
      path: '/marketPlace/$marketPlaceId/$marketPlaceId'
      fullPath: '/marketPlace/$marketPlaceId/$marketPlaceId'
      preLoaderRoute: typeof dashboardMarketPlaceMarketPlaceIdMarketPlaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GetstartedRoute: GetstartedRoute,
  dashboardUsersUserIdRoute: dashboardUsersUserIdRoute,
  dashboardAccountIndexRoute: dashboardAccountIndexRoute,
  dashboardCategoryRequestIndexRoute: dashboardCategoryRequestIndexRoute,
  dashboardMarketPlaceIndexRoute: dashboardMarketPlaceIndexRoute,
  dashboardResolutionIndexRoute: dashboardResolutionIndexRoute,
  dashboardSettingsIndexRoute: dashboardSettingsIndexRoute,
  dashboardSkillsIndexRoute: dashboardSkillsIndexRoute,
  dashboardSummaryIndexRoute: dashboardSummaryIndexRoute,
  dashboardUsersIndexRoute: dashboardUsersIndexRoute,
  dashboardWalletIndexRoute: dashboardWalletIndexRoute,
  dashboardMarketPlaceMarketPlaceIdMarketPlaceIdRoute:
    dashboardMarketPlaceMarketPlaceIdMarketPlaceIdRoute,
  dashboardMarketPlaceMarketPlaceIdChatRoute:
    dashboardMarketPlaceMarketPlaceIdChatRoute,
  dashboardSkillsCategoryIdSubCategoryIdRoute:
    dashboardSkillsCategoryIdSubCategoryIdRoute,
  dashboardMarketPlaceMarketPlaceIdIndexRoute:
    dashboardMarketPlaceMarketPlaceIdIndexRoute,
  dashboardSkillsCategoryIdIndexRoute: dashboardSkillsCategoryIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
